const commentCopy={
 de:{title:'Gastkommentare',empty:'Noch keine freigegebenen Kommentare.',loading:'Kommentare werden geladen ...',name:'Name',comment:'Dein Kommentar',send:'Zur Freigabe senden',pending:'Danke! Dein Kommentar wird vor der Veröffentlichung geprüft.',failed:'Der Kommentar konnte nicht gesendet werden. Bitte versuche es später erneut.',note:'Kommentare erscheinen nach Prüfung durch die Moderation.',login:'Moderatoren-Login',loginIntro:'Geschützter Bereich für die SlushyWeb-Redaktion.',email:'E-Mail',password:'Passwort',signIn:'Sicher anmelden',signOut:'Abmelden',queue:'Moderation',queueIntro:'Neue Gastkommentare prüfen und verwalten.',waiting:'wartend',noQueue:'Alles erledigt. Es gibt keine offenen Kommentare.',approve:'Freigeben',reject:'Ablehnen',remove:'Löschen',unauthorized:'Dieses Konto besitzt keine Moderationsrechte.'},
 en:{title:'Guest comments',empty:'No approved comments yet.',loading:'Loading comments ...',name:'Name',comment:'Your comment',send:'Submit for review',pending:'Thank you! Your comment will be reviewed before it appears.',failed:'The comment could not be submitted. Please try again later.',note:'Comments appear after moderator approval.',login:'Moderator login',loginIntro:'Protected workspace for the SlushyWeb editorial team.',email:'Email',password:'Password',signIn:'Sign in securely',signOut:'Sign out',queue:'Moderation',queueIntro:'Review and manage new guest comments.',waiting:'waiting',noQueue:'All caught up. There are no comments waiting.',approve:'Approve',reject:'Reject',remove:'Delete',unauthorized:'This account has no moderation rights.'}
};
const config=window.slushySupabaseConfig;
const commentClient=config&&window.supabase?window.supabase.createClient(config.url,config.publishableKey):null;
let commentFormStartedAt=Date.now();

function commentSectionMarkup(recipeId){const c=commentCopy[lang];commentFormStartedAt=Date.now();return `<section class="recipe-comments" data-recipe-id="${recipeId}"><h3>${c.title}</h3><div class="comment-list" aria-live="polite"><p class="comment-state">${c.loading}</p></div><form class="comment-box"><input name="author_name" required minlength="2" maxlength="60" placeholder="${c.name}"><textarea name="body" rows="4" required minlength="3" maxlength="1200" placeholder="${c.comment}"></textarea><input class="comment-honeypot" name="website" tabindex="-1" autocomplete="off" aria-hidden="true"><button type="submit" class="comment-submit">${c.send}</button><p class="comment-note">${c.note}</p><p class="comment-feedback" role="status"></p></form></section>`}

async function initRecipeComments(recipeId){const section=document.querySelector(`.recipe-comments[data-recipe-id="${recipeId}"]`);if(!section)return;const list=section.querySelector('.comment-list'),form=section.querySelector('form');await loadRecipeComments(recipeId,list);form.onsubmit=async event=>{event.preventDefault();const c=commentCopy[lang],feedback=form.querySelector('.comment-feedback'),button=form.querySelector('button'),data=new FormData(form);button.disabled=true;feedback.textContent='';try{if(!commentClient)throw new Error('Supabase is not configured');const response=await fetch(`${config.url}/functions/v1/submit-comment`,{method:'POST',headers:{'Content-Type':'application/json',apikey:config.publishableKey},body:JSON.stringify({recipe_id:recipeId,author_name:data.get('author_name'),body:data.get('body'),website:data.get('website'),language:lang,elapsed_ms:Date.now()-commentFormStartedAt})});if(!response.ok)throw new Error(`Submission failed: ${response.status}`);form.reset();commentFormStartedAt=Date.now();feedback.textContent=c.pending}catch(error){console.error(error);feedback.textContent=c.failed}finally{button.disabled=false}}}

async function loadRecipeComments(recipeId,container){const c=commentCopy[lang];if(!commentClient){container.innerHTML=`<p class="comment-state">${c.failed}</p>`;return}const{data,error}=await commentClient.from('comments').select('id,author_name,body,created_at').eq('recipe_id',recipeId).eq('status','approved').order('created_at',{ascending:false});if(error){console.error(error);container.innerHTML=`<p class="comment-state">${c.failed}</p>`;return}container.replaceChildren();if(!data.length){const empty=document.createElement('p');empty.className='comment-state';empty.textContent=c.empty;container.append(empty);return}data.forEach(item=>{const article=document.createElement('article'),heading=document.createElement('div'),author=document.createElement('strong'),date=document.createElement('time'),body=document.createElement('p');author.textContent=item.author_name;date.dateTime=item.created_at;date.textContent=new Intl.DateTimeFormat(lang,{dateStyle:'medium'}).format(new Date(item.created_at));body.textContent=item.body;heading.append(author,date);article.append(heading,body);container.append(article)})}

const moderatorDialog=document.querySelector('#moderatorDialog');
document.querySelector('#moderatorOpen').onclick=()=>{moderatorDialog.showModal();renderModerator()};
document.querySelector('.moderator-close').onclick=()=>moderatorDialog.close();
async function renderModerator(message=''){
 const c=commentCopy[lang],auth=document.querySelector('#moderatorAuth'),queue=document.querySelector('#moderatorQueue');
 const sessionResult=commentClient?await commentClient.auth.getSession():{data:{session:null}},session=sessionResult.data.session;
 if(!session){
  queue.replaceChildren();
  auth.innerHTML=`<form id="moderatorLogin"><div class="moderator-brand"><span>S</span><div><small>SlushyWeb</small><h2>${c.login}</h2></div></div><p class="moderator-intro">${c.loginIntro}</p><label>${c.email}<input type="email" name="email" required autocomplete="email"></label><label>${c.password}<input type="password" name="password" required autocomplete="current-password"></label><button class="moderator-primary" type="submit">${c.signIn}<span aria-hidden="true">→</span></button><p class="moderator-message" role="status">${message}</p></form>`;
  document.querySelector('#moderatorLogin').onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button'),formData=new FormData(event.currentTarget);button.disabled=true;const result=await commentClient.auth.signInWithPassword({email:formData.get('email'),password:formData.get('password')});if(result.error)return renderModerator(result.error.message);const role=await commentClient.from('moderators').select('user_id').eq('user_id',result.data.user.id).maybeSingle();if(!role.data){await commentClient.auth.signOut();return renderModerator(c.unauthorized)}renderModerator()};
  return;
 }
 const{data,error}=await commentClient.from('comments').select('id,recipe_id,author_name,body,created_at,status').order('created_at',{ascending:true});
 if(error){queue.textContent=error.message;return}
 const pending=data.filter(item=>item.status==='pending');
 auth.innerHTML=`<div class="moderator-heading"><div><span class="moderator-kicker">SlushyWeb Studio</span><h2>${c.queue}</h2><p>${c.queueIntro}</p></div><div class="moderator-heading-actions"><span class="queue-count"><strong>${pending.length}</strong> ${c.waiting}</span><button id="moderatorLogout" type="button">${c.signOut}</button></div></div>`;
 document.querySelector('#moderatorLogout').onclick=async()=>{await commentClient.auth.signOut();renderModerator()};
 queue.replaceChildren();
 if(!pending.length){queue.innerHTML=`<div class="moderation-empty"><span aria-hidden="true">✓</span><p>${c.noQueue}</p></div>`;return}
 pending.forEach(item=>{
  const article=document.createElement('article'),top=document.createElement('div'),meta=document.createElement('div'),badge=document.createElement('span'),title=document.createElement('strong'),date=document.createElement('time'),body=document.createElement('p'),actions=document.createElement('div');
  const recipe=recipes.find(recipe=>recipe[0]===item.recipe_id),recipeName=recipe?(lang==='de'?recipe[1]:recipe[2]):item.recipe_id;
  article.className='moderation-item';top.className='moderation-item-top';meta.className='moderation-meta';actions.className='moderation-actions';badge.className='moderation-recipe';badge.textContent=recipeName;title.textContent=item.author_name;date.dateTime=item.created_at;date.textContent=new Intl.DateTimeFormat(lang,{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.created_at));body.textContent=item.body;meta.append(title,date);top.append(badge,meta);
  [['approved',c.approve],['rejected',c.reject],['delete',c.remove]].forEach(([action,label])=>{const button=document.createElement('button');button.type='button';button.className=`action-${action}`;button.textContent=label;button.onclick=async()=>{button.disabled=true;await moderateComment(item.id,action,session.user.id);renderModerator()};actions.append(button)});
  article.append(top,body,actions);queue.append(article);
 })
}
async function moderateComment(id,action,moderatorId){if(action==='delete')return commentClient.from('comments').delete().eq('id',id);return commentClient.from('comments').update({status:action,moderated_at:new Date().toISOString(),moderated_by:moderatorId}).eq('id',id)}
